config/routes.rb
FirstApp::Application.routes.draw do

  get '/signin',     :to => 'sessions#new'
  get '/signout',    :to => 'sessions#destroy'
  get '/:championship_name/ranking', :to => 'stats#show_ranking'
  get '/:championship_name/matches/played', :to => 'stats#show_played_matches'
  get '/:championship_name/matches/future', :to => 'stats#show_future_matches'
  get '/:championship_name/teams/:team_name', :to => 'stats#show_team'
  get '/:championship_name/matches/:match_id', :to => 'stats#show_match'

  root :to => 'stats#show_home'

  get "sessions/new"

  resources :timekeepers

  post 'matches/matchsheet/:id/', :to => 'matches#matchsheet'
  resources :matches

  resources :gyms

  resources :members

  resources :championships

  resources :seasons

  resources :clubs

  resources :federations

  get 'teams/:id/getPlayers/', :to => 'teams#getPlayers'
  resources :teams

  resources :microposts

  resources :users
  resources :timekeepers

  resources :facts, :type => 'Fact', :controller => 'facts'
  resources :goals, :type => 'Goal', :controller => 'facts'
  resources :cards, :type => 'Card', :controller => 'facts'

  resources :participants, :type => 'Participant', :controller => 'participants'
  resources :coaches, :type => 'Coach', :controller => 'participants'
  resources :players, :type => 'Player', :controller => 'participants'
  resources :referees, :type => 'Referee', :controller => 'participants'

  resources :sessions, :only => [:new, :create, :destroy]

end

app/models/card.rb
class YellowCard < Fact
end

app/models/club.rb
class Club < ActiveRecord::Base
	has_many :timekeeper

	attr_accessible :name, :adress, :zip, :city
end

app/models/coach.rb
class Coach < Participant
end

app/models/fact.rb
class Fact < ActiveRecord::Base
	attr_accessible :time, :type, :match_id, :player_id
	belongs_to :match
	belongs_to :player
	
	self.inheritance_column = :type 
end

app/models/fact_goal.rb
class Goal < Fact
end

app/models/federation.rb
class Federation < ActiveRecord::Base

	has_many :championships 
  	has_many :members
  	has_many :gyms

  	attr_accessible :name
end

app/models/foul.rb
class Foul < Fact
end

app/models/goal.rb
class Goal < Fact
end

app/models/gym.rb
class Gym < ActiveRecord::Base
  	belongs_to :federation
    has_many :matches

    attr_accessible :name, :adress, :zip, :city, :federation_id
end

app/models/match.rb
class Match < ActiveRecord::Base
  belongs_to :championship
  belongs_to :gym
  belongs_to :referee
  belongs_to :team, :class_name => "Team", :foreign_key => "team_id1_id"
  belongs_to :team, :class_name => "Team", :foreign_key => "team_id2_id"
  has_many :facts

  def team1
  	Team.find_by_id(self.team_id1_id)
  end

  def team2
  	Team.find_by_id(self.team_id2_id)
  end
end

app/models/member.rb
class Member < ActiveRecord::Base
  belongs_to :federation

# Crée automatique l'attribut virtuel 'password_confirmation'.
  validates :password,         :presence     => true,
                               :confirmation => true,
                               :length       => { :within => 4..40 }

  validates :login,          :presence => true,
                                  :length   => { :maximum => 50 }

  before_save :encrypt_password

  def self.authenticate(login, password)
          user = find_by_login(login)
          return nil if user.nil?
          return user if user.password== user.encrypt(password)
  end

  def self.authenticate_with_encrypted_password(login, password)
    user = find_by_login(login)
    return nil if user.nil?
    return user if user.password == password
  end

  def encrypt(string)
    Digest::SHA2.hexdigest(string)
  end

  private

    def encrypt_password 
      self.password = encrypt(password)
    end
end

app/models/micropost.rb
class Micropost < ActiveRecord::Base
  attr_accessible :content, :user_id
  belongs_to :user
  validates :content, :length => { :maximum => 140 }
end

app/models/penalty.rb
class Penalty < Fact
end

app/models/player.rb
class Player < Participant
end

app/models/ranking.rb
class Ranking < ActiveRecord::Base
end

app/models/referee.rb
class Referee < Participant
	has_many :matches
end

app/models/season.rb
class Season < ActiveRecord::Base
end

app/models/show_team.rb
class ShowTeam < ActiveRecord::Base
end

app/models/team.rb
class Team < ActiveRecord::Base
  belongs_to :club
  belongs_to :referee
  has_many :matches

  has_many :participantTeams
  has_many :participants, :through => :participantTeams

  attr_accessible :name, :homeColor, :awayColor, :club_id

  def players 
  	self.participants.find(:all, :conditions => {:type => 'Player'})
  end

 def display_name
    "#{name} -  #{club.name}"
  end

  def coach
    self.participants.find_by_type("Coach")
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :nom
  has_many :microposts
end

app/models/win_lose.rb
class WinLose < ActiveRecord::Base
end

app/controllers/federations_controller.rb
class FederationsController < ApplicationController
  before_action :set_federation, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate

  # GET /federations
  def index
    @federations = Federation.all

    respond_to do |format|
      format.html 
      format.json { render json: @federations }
    end
  end

  # GET /federations/1
  def show

    respond_to do |format|
      format.html 
      format.json { render json: @federation }
    end
  end

  # GET /federations/new
  def new
    @federation = Federation.new
  end

  # GET /federations/1/edit
  def edit
  end

  # POST /federations
  def create
    @federation = Federation.new(federation_params)

    if @federation.save
      redirect_to @federation, notice: 'La fédération a été ajoutée'
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /federations/1
  def update
    if @federation.update(federation_params)
      redirect_to @federation, notice: 'La fédération a été modifiée'
    else
      render action: 'edit'
    end
  end

  # DELETE /federations/1
  def destroy
    @federation.destroy
    redirect_to federations_url, notice: 'La fédération a été supprimée'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_federation
      @federation = Federation.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def federation_params
      params.require(:federation).permit(:name)
    end
end

app/helpers/federations_helper.rb
module FederationsHelper
end

app/views/federations/_form.html.erb
<%= form_for(@federation) do |f| %>
  <% if @federation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@federation.errors.count, "error") %> prohibited this federation from being saved:</h2>

      <ul>
      <% @federation.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label "Nom" %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions btn">
    <%= f.submit %>
  </div>
<% end %>

app/views/federations/edit.html.erb
<h1>Modifier la fédération</h1>

<%= render 'form' %>

<%= link_to 'Voir', @federation %> |
<%= link_to 'Retour', federations_path %>

app/views/federations/index.html.erb
<h1>Liste des fédérations</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Nom</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @federations.each do |federation| %>
      <tr>
        <td><%= federation.name %></td>
        <td><%= link_to 'Voir', federation %></td>
        <td><%= link_to 'Modifier', edit_federation_path(federation) %></td>
        <td><%= link_to 'Supprimer', federation, method: :delete, data: { confirm: 'Etes-vous sûr?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to '<button type="button" class="btn btn-danger">Ajouter une fédération</button>'.html_safe, new_federation_path %>

app/views/federations/new.html.erb
<h1>Ajouter une fédération</h1>

<%= render 'form' %>

<%= link_to 'Retour', federations_path %>

app/views/federations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nom:</strong>
  <%= @federation.name %>
</p>

<%= link_to 'Modifier', edit_federation_path(@federation) %> |
<%= link_to 'Retour', federations_path %>