config/routes.rb
FirstApp::Application.routes.draw do

  get '/signin',     :to => 'sessions#new'
  get '/signout',    :to => 'sessions#destroy'
  get '/:championship_name/ranking', :to => 'stats#show_ranking'
  get '/:championship_name/matches/played', :to => 'stats#show_played_matches'
  get '/:championship_name/matches/future', :to => 'stats#show_future_matches'
  get '/:championship_name/teams/:team_name', :to => 'stats#show_team'
  get '/:championship_name/matches/:match_id', :to => 'stats#show_match'

  root :to => 'stats#show_home'

  get "sessions/new"

  resources :timekeepers

  post 'matches/matchsheet/:id/', :to => 'matches#matchsheet'
  resources :matches

  resources :gyms

  resources :members

  resources :championships

  resources :seasons

  resources :clubs

  resources :federations

  get 'teams/:id/getPlayers/', :to => 'teams#getPlayers'
  resources :teams

  resources :microposts

  resources :users
  resources :timekeepers

  resources :facts, :type => 'Fact', :controller => 'facts'
  resources :goals, :type => 'Goal', :controller => 'facts'
  resources :cards, :type => 'Card', :controller => 'facts'

  resources :participants, :type => 'Participant', :controller => 'participants'
  resources :coaches, :type => 'Coach', :controller => 'participants'
  resources :players, :type => 'Player', :controller => 'participants'
  resources :referees, :type => 'Referee', :controller => 'participants'

  resources :sessions, :only => [:new, :create, :destroy]

end

app/models/card.rb
class YellowCard < Fact
end

app/models/club.rb
class Club < ActiveRecord::Base
	has_many :timekeeper

	attr_accessible :name, :adress, :zip, :city
end

app/models/coach.rb
class Coach < Participant
end

app/models/fact.rb
class Fact < ActiveRecord::Base
	attr_accessible :time, :type, :match_id, :player_id
	belongs_to :match
	belongs_to :player
	
	self.inheritance_column = :type 
end

app/models/fact_goal.rb
class Goal < Fact
end

app/models/foul.rb
class Foul < Fact
end

app/models/goal.rb
class Goal < Fact
end

app/models/gym.rb
class Gym < ActiveRecord::Base
  	belongs_to :federation
    has_many :matches

    attr_accessible :name, :adress, :zip, :city, :federation_id
end

app/models/match.rb
class Match < ActiveRecord::Base
  belongs_to :championship
  belongs_to :gym
  belongs_to :referee
  belongs_to :team, :class_name => "Team", :foreign_key => "team_id1_id"
  belongs_to :team, :class_name => "Team", :foreign_key => "team_id2_id"
  has_many :facts

  def team1
  	Team.find_by_id(self.team_id1_id)
  end

  def team2
  	Team.find_by_id(self.team_id2_id)
  end
end

app/models/member.rb
class Member < ActiveRecord::Base
  belongs_to :federation

# Crée automatique l'attribut virtuel 'password_confirmation'.
  validates :password,         :presence     => true,
                               :confirmation => true,
                               :length       => { :within => 4..40 }

  validates :login,          :presence => true,
                                  :length   => { :maximum => 50 }

  before_save :encrypt_password

  def self.authenticate(login, password)
          user = find_by_login(login)
          return nil if user.nil?
          return user if user.password== user.encrypt(password)
  end

  def self.authenticate_with_encrypted_password(login, password)
    user = find_by_login(login)
    return nil if user.nil?
    return user if user.password == password
  end

  def encrypt(string)
    Digest::SHA2.hexdigest(string)
  end

  private

    def encrypt_password 
      self.password = encrypt(password)
    end
end

app/models/micropost.rb
class Micropost < ActiveRecord::Base
  attr_accessible :content, :user_id
  belongs_to :user
  validates :content, :length => { :maximum => 140 }
end

app/models/penalty.rb
class Penalty < Fact
end

app/models/player.rb
class Player < Participant
end

app/models/ranking.rb
class Ranking < ActiveRecord::Base
end

app/models/referee.rb
class Referee < Participant
	has_many :matches
end

app/models/season.rb
class Season < ActiveRecord::Base
end

app/models/show_team.rb
class ShowTeam < ActiveRecord::Base
end

app/models/team.rb
class Team < ActiveRecord::Base
  belongs_to :club
  belongs_to :referee
  has_many :matches

  has_many :participantTeams
  has_many :participants, :through => :participantTeams

  attr_accessible :name, :homeColor, :awayColor, :club_id

  def players 
  	self.participants.find(:all, :conditions => {:type => 'Player'})
  end

 def display_name
    "#{name} -  #{club.name}"
  end

  def coach
    self.participants.find_by_type("Coach")
  end
end

app/models/timekeeper.rb
class Timekeeper < ActiveRecord::Base
  belongs_to :club

  attr_accessible :login, :password, :password_confirmation, :club_id

  # Crée automatique l'attribut virtuel 'password_confirmation'.
  validates :password,         :presence     => true,
                               :confirmation => true,
                               :length       => { :within => 4..40 }

  validates :login,          :presence => true,
                                  :length   => { :maximum => 50 }

  before_save :encrypt_password

  def self.authenticate(login, password)
          user = find_by_login(login)
          return nil if user.nil?
          return user if user.password== user.encrypt(password)
  end

  def self.authenticate_with_encrypted_password(login, password)
    user = find_by_login(login)
    return nil if user.nil?
    return user if user.password == password
  end

  def encrypt(string)
    Digest::SHA2.hexdigest(string)
  end

  private

    def encrypt_password 
      self.password = encrypt(password)
    end
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :nom
  has_many :microposts
end

app/models/win_lose.rb
class WinLose < ActiveRecord::Base
end

app/controllers/timekeepers_controller.rb
class TimekeepersController < ApplicationController
  before_action :set_timekeeper, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate


  # GET /timekeepers
  def index
    @timekeepers = Timekeeper.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @timekeepers }
    end
  end

  # GET /timekeepers/1
  def show
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: nil }
    end
  end

  # GET /timekeepers/new
  def new
    @timekeeper = Timekeeper.new
  end

  # GET /timekeepers/1/edit
  def edit
  end

  # POST /timekeepers
  def create
    @timekeeper = Timekeeper.new(timekeeper_params)

    if @timekeeper.save
      sign_in @timekeeper
      redirect_to @timekeeper, notice: 'Le chronomètreur a été ajouté'
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /timekeepers/1
  def update
    if @timekeeper.update(timekeeper_params)
      redirect_to @timekeeper, notice: 'Le chronomètreur a été modifié'
    else
      render action: 'edit'
    end
  end

  # DELETE /timekeepers/1
  def destroy
    @timekeeper.destroy
    redirect_to timekeepers_url, notice: 'Le chronomètreur a été supprimé'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_timekeeper
      @timekeeper = Timekeeper.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def timekeeper_params
      params.require(:timekeeper).permit(:login, :password,:password_confirmation, :club_id)
    end
end

app/helpers/timekeepers_helper.rb
module TimekeepersHelper
end

app/views/timekeepers/_form.html.erb
<%= form_for(@timekeeper) do |f| %>
  <% if @timekeeper.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@timekeeper.errors.count, "error") %> prohibited this timekeeper from being saved:</h2>

      <ul>
      <% @timekeeper.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label "Utilisateur" %><br>
    <%= f.text_field :login %>
  </div>
  <div class="field">
    <%= f.label "Mot de passe" %><br>  
    <%= f.password_field :password %>
  </div>
    <div class="field">
    <%= f.label "Confirmation de mot de passe" %><br>  
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="field">
    <%= f.label "Club" %><br>
    <%= collection_select(:timekeeper, :club_id, Club.all, :id , :name)%>
  </div>
  <div class="actions btn">
    <%= f.submit %>
  </div>
<% end %>

app/views/timekeepers/edit.html.erb
<h1>Modifier le chronométreur</h1>

<%= render 'form' %>

<%= link_to 'Voir', @timekeeper %> |
<%= link_to 'Retour', timekeepers_path %>

app/views/timekeepers/index.html.erb
<h1>Liste des chronométreurs</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Login</th>
      <th>Club</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @timekeepers.each do |timekeeper| %>
      <tr>
        <td><%= timekeeper.login %></td>
        <td><%= timekeeper.club.name %></td>
        <td><%= link_to 'Voir', timekeeper %></td>
        <td><%= link_to 'Modifier', edit_timekeeper_path(timekeeper) %></td>
        <td><%= link_to 'Supprimer', timekeeper, method: :delete, data: { confirm: 'Etes-vous sûr?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to '<button type="button" class="btn btn-danger">Ajouter un chronométreur</button>'.html_safe, new_timekeeper_path %>

app/views/timekeepers/new.html.erb
<h1>Inscription</h1>

<%= render 'form' %>

<%= link_to 'Retour', timekeeper_path %>

app/views/timekeepers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Login:</strong>
  <%= @timekeeper.login %>
</p>

<p>
  <strong>Club:</strong>
  <%= @timekeeper.club.name %>
</p>

<%= link_to 'Modifier', edit_timekeeper_path(@timekeeper) %> |
<%= link_to 'Retour', timekeepers_path %>