config/routes.rb
FirstApp::Application.routes.draw do

  get '/signin',     :to => 'sessions#new'
  get '/signout',    :to => 'sessions#destroy'
  get '/:championship_name/ranking', :to => 'stats#show_ranking'
  get '/:championship_name/matches/played', :to => 'stats#show_played_matches'
  get '/:championship_name/matches/future', :to => 'stats#show_future_matches'
  get '/:championship_name/teams/:team_name', :to => 'stats#show_team'
  get '/:championship_name/matches/:match_id', :to => 'stats#show_match'

  root :to => 'stats#show_home'

  get "sessions/new"

  resources :timekeepers

  post 'matches/matchsheet/:id/', :to => 'matches#matchsheet'
  resources :matches

  resources :gyms

  resources :members

  resources :championships

  resources :seasons

  resources :clubs

  resources :federations

  get 'teams/:id/getPlayers/', :to => 'teams#getPlayers'
  resources :teams

  resources :microposts

  resources :users
  resources :timekeepers

  resources :facts, :type => 'Fact', :controller => 'facts'
  resources :goals, :type => 'Goal', :controller => 'facts'
  resources :cards, :type => 'Card', :controller => 'facts'

  resources :participants, :type => 'Participant', :controller => 'participants'
  resources :coaches, :type => 'Coach', :controller => 'participants'
  resources :players, :type => 'Player', :controller => 'participants'
  resources :referees, :type => 'Referee', :controller => 'participants'

  resources :sessions, :only => [:new, :create, :destroy]

end

app/models/card.rb
class YellowCard < Fact
end

app/models/club.rb
class Club < ActiveRecord::Base
	has_many :timekeeper

	attr_accessible :name, :adress, :zip, :city
end

app/models/coach.rb
class Coach < Participant
end

app/models/fact.rb
class Fact < ActiveRecord::Base
	attr_accessible :time, :type, :match_id, :player_id
	belongs_to :match
	belongs_to :player
	
	self.inheritance_column = :type 
end

app/models/fact_goal.rb
class Goal < Fact
end

app/models/foul.rb
class Foul < Fact
end

app/models/goal.rb
class Goal < Fact
end

app/models/gym.rb
class Gym < ActiveRecord::Base
  	belongs_to :federation
    has_many :matches

    attr_accessible :name, :adress, :zip, :city, :federation_id
end

app/models/match.rb
class Match < ActiveRecord::Base
  belongs_to :championship
  belongs_to :gym
  belongs_to :referee
  belongs_to :team, :class_name => "Team", :foreign_key => "team_id1_id"
  belongs_to :team, :class_name => "Team", :foreign_key => "team_id2_id"
  has_many :facts

  def team1
  	Team.find_by_id(self.team_id1_id)
  end

  def team2
  	Team.find_by_id(self.team_id2_id)
  end
end

app/models/member.rb
class Member < ActiveRecord::Base
  belongs_to :federation

# Crée automatique l'attribut virtuel 'password_confirmation'.
  validates :password,         :presence     => true,
                               :confirmation => true,
                               :length       => { :within => 4..40 }

  validates :login,          :presence => true,
                                  :length   => { :maximum => 50 }

  before_save :encrypt_password

  def self.authenticate(login, password)
          user = find_by_login(login)
          return nil if user.nil?
          return user if user.password== user.encrypt(password)
  end

  def self.authenticate_with_encrypted_password(login, password)
    user = find_by_login(login)
    return nil if user.nil?
    return user if user.password == password
  end

  def encrypt(string)
    Digest::SHA2.hexdigest(string)
  end

  private

    def encrypt_password 
      self.password = encrypt(password)
    end
end

app/models/micropost.rb
class Micropost < ActiveRecord::Base
  attr_accessible :content, :user_id
  belongs_to :user
  validates :content, :length => { :maximum => 140 }
end

app/models/penalty.rb
class Penalty < Fact
end

app/models/player.rb
class Player < Participant
end

app/models/ranking.rb
class Ranking < ActiveRecord::Base
end

app/models/referee.rb
class Referee < Participant
	has_many :matches
end

app/models/season.rb
class Season < ActiveRecord::Base
end

app/models/show_team.rb
class ShowTeam < ActiveRecord::Base
end

app/models/team.rb
class Team < ActiveRecord::Base
  belongs_to :club
  belongs_to :referee
  has_many :matches

  has_many :participantTeams
  has_many :participants, :through => :participantTeams

  attr_accessible :name, :homeColor, :awayColor, :club_id

  def players 
  	self.participants.find(:all, :conditions => {:type => 'Player'})
  end

 def display_name
    "#{name} -  #{club.name}"
  end

  def coach
    self.participants.find_by_type("Coach")
  end
end

app/models/team_fact.rb
class TeamFact < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :nom
  has_many :microposts
end

app/models/win_lose.rb
class WinLose < ActiveRecord::Base
end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController
  before_action :set_match, only: [:show, :edit, :update, :destroy, :matchsheet]
  before_filter :authenticate

  skip_before_filter :verify_authenticity_token, :only => [:matchsheet]


  # GET /matches
  def index
    @matches = Match.all

    respond_to do |format|
      format.html #
      format.json { render json: @matches }
    end
  end

  # GET /matches/1
  def show
    @match = Match.find(params[:id])

    respond_to do |format|
      format.html 
      format.json { render json: @match }
    end
  end

  # GET /matches/new
  def new
    @match = Match.new
  end

  # GET /matches/1/edit
  def edit
  end

  # POST /matches
  def create
    @match = Match.new(match_params)

    if @match.save
      redirect_to @match, notice: 'Match ajouté correctement'
    else
      render action: 'new'
    end
  end 

  #POST /matches/matchsheet/1
  def matchsheet
    params["facts"].each do |f|
      @match.facts << Fact.new(f)
    end
    @match.update(match_params)
    render json: "true"
  end

  # PATCH/PUT /matches/1
  def update
    if @match.update(match_params)
      redirect_to @match, notice: 'Le match a été mis à jour'
    else
      render action: 'edit'
    end
  end

  # DELETE /matches/1
  def destroy
    @match.destroy
    redirect_to matches_url, notice: 'Le match à été supprimé'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_match
      @match = Match.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def match_params
      params.require(:match).permit(:date, :homeScore, :awayScore, :championship_id, :gym_id, :team_id1_id, :team_id2_id, :referee_id)
    end
end

app/helpers/matches_helper.rb
module MatchesHelper
end

app/views/matches/_form.html.erb
<%= form_for(@match) do |f| %>
  <% if @match.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@match.errors.count, "error") %> prohibited this match from being saved:</h2>

      <ul>
      <% @match.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label "Date" %><br>
    <%= f.datetime_select :date %>
  </div>
  <div class="field">
    <%= f.label "Championnat" %><br>
    <%= collection_select(:match, :championship_id, Championship.all, :id , :name) %>
  </div>
  <div class="field">
    <%= f.label "Salle" %><br>
    <%= collection_select(:match, :gym_id, Gym.all, :id , :name) %>
  </div>
  <div class="field">
    <%= f.label "Arbitre" %><br>
    <%= collection_select(:match, :referee_id, Referee.all, :id , :display_name) %>
  </div>
  <div class="field">
    <%= f.label "Equipe hôte" %><br>
    <%= collection_select(:match, :team_id1_id, Team.all, :id , :display_name) %>
  </div>
  <div class="field">
    <%= f.label "Equipe visiteuse" %><br>
    <%= collection_select(:match, :team_id2_id, Team.all, :id , :display_name) %>
  </div>
  <div class="actions btn">
    <%= f.submit %>
  </div>
<% end %>

app/views/matches/edit.html.erb
<h1>Modifier le match</h1>

<%= render 'form' %>

<%= link_to 'Voir', @match %> |
<%= link_to 'Retour', matches_path %>

app/views/matches/index.html.erb
<h1>Liste des matchs</h1>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Date</th>
      <th>Championnat</th>
      <th>Salle</th>
      <th>Arbitre</th>
      <th>Hôte</th>
      <th>Visiteurs</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @matches.each do |match| %>
      <tr>
        <td><%= match.date.to_formatted_s(:short)  %></td>
        <td><%= match.championship.name %></td>
        <td><%= match.gym.name %></td>
        <td><%= if !match.referee.nil? then match.referee.display_name end %></td>
        <td><%= match.team1.display_name %></td>
        <td><%= match.team2.display_name %></td>
        <td><%= link_to 'Voir', match %></td>
        <td><%= link_to 'Modifier', edit_match_path(match) %></td>
        <td><%= link_to 'Supprimer', match, method: :delete, data: { confirm: 'Etes vous sur ?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to '<button type="button" class="btn btn-danger">Ajouter un match</button>'.html_safe, new_match_path %>

app/views/matches/new.html.erb
<h1>Ajouter un match</h1>

<%= render 'form' %>

<%= link_to 'Retour', matches_path %>

app/views/matches/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date:</strong>
  <%= @match.date %>
</p>

<p>
  <strong>Championnat:</strong>
  <%= @match.championship.name %>
</p>

<p>
  <strong>Salle:</strong>
  <%= @match.gym.name %>
</p>

<p>
  <strong>Equipe hôte :</strong>
  <%= @match.team1.display_name %>
</p>

<p>
  <strong>Equipe visiteuse</strong>
  <%= @match.team2.display_name %>
</p>

<%= link_to 'Modifier', edit_match_path(@match) %> |
<%= link_to 'Retour', matches_path %>