config/routes.rb
FirstApp::Application.routes.draw do

  get '/signin',     :to => 'sessions#new'
  get '/signout',    :to => 'sessions#destroy'
  get '/:championship_name/ranking', :to => 'stats#show_ranking'
  get '/:championship_name/matches/played', :to => 'stats#show_played_matches'
  get '/:championship_name/matches/future', :to => 'stats#show_future_matches'
  get '/:championship_name/teams/:team_name', :to => 'stats#show_team'
  get '/:championship_name/matches/:match_id', :to => 'stats#show_match'

  root :to => 'stats#show_home'

  get "sessions/new"

  resources :timekeepers

  post 'matches/matchsheet/:id/', :to => 'matches#matchsheet'
  resources :matches

  resources :gyms

  resources :members

  resources :championships

  resources :seasons

  resources :clubs

  resources :federations

  get 'teams/:id/getPlayers/', :to => 'teams#getPlayers'
  resources :teams

  resources :microposts

  resources :users
  resources :timekeepers

  resources :facts, :type => 'Fact', :controller => 'facts'
  resources :goals, :type => 'Goal', :controller => 'facts'
  resources :cards, :type => 'Card', :controller => 'facts'

  resources :participants, :type => 'Participant', :controller => 'participants'
  resources :coaches, :type => 'Coach', :controller => 'participants'
  resources :players, :type => 'Player', :controller => 'participants'
  resources :referees, :type => 'Referee', :controller => 'participants'

  resources :sessions, :only => [:new, :create, :destroy]

end

app/models/card.rb
class YellowCard < Fact
end

app/models/club.rb
class Club < ActiveRecord::Base
	has_many :timekeeper

	attr_accessible :name, :adress, :zip, :city
end

app/models/coach.rb
class Coach < Participant
end

app/models/fact.rb
class Fact < ActiveRecord::Base
	attr_accessible :time, :type, :match_id, :player_id
	belongs_to :match
	belongs_to :player
	
	self.inheritance_column = :type 
end

app/models/fact_goal.rb
class Goal < Fact
end

app/models/foul.rb
class Foul < Fact
end

app/models/goal.rb
class Goal < Fact
end

app/models/gym.rb
class Gym < ActiveRecord::Base
  	belongs_to :federation
    has_many :matches

    attr_accessible :name, :adress, :zip, :city, :federation_id
end

app/models/match.rb
class Match < ActiveRecord::Base
  belongs_to :championship
  belongs_to :gym
  belongs_to :referee
  belongs_to :team, :class_name => "Team", :foreign_key => "team_id1_id"
  belongs_to :team, :class_name => "Team", :foreign_key => "team_id2_id"
  has_many :facts

  def team1
  	Team.find_by_id(self.team_id1_id)
  end

  def team2
  	Team.find_by_id(self.team_id2_id)
  end
end

app/models/member.rb
class Member < ActiveRecord::Base
  belongs_to :federation

# Crée automatique l'attribut virtuel 'password_confirmation'.
  validates :password,         :presence     => true,
                               :confirmation => true,
                               :length       => { :within => 4..40 }

  validates :login,          :presence => true,
                                  :length   => { :maximum => 50 }

  before_save :encrypt_password

  def self.authenticate(login, password)
          user = find_by_login(login)
          return nil if user.nil?
          return user if user.password== user.encrypt(password)
  end

  def self.authenticate_with_encrypted_password(login, password)
    user = find_by_login(login)
    return nil if user.nil?
    return user if user.password == password
  end

  def encrypt(string)
    Digest::SHA2.hexdigest(string)
  end

  private

    def encrypt_password 
      self.password = encrypt(password)
    end
end

app/models/micropost.rb
class Micropost < ActiveRecord::Base
  attr_accessible :content, :user_id
  belongs_to :user
  validates :content, :length => { :maximum => 140 }
end

app/models/penalty.rb
class Penalty < Fact
end

app/models/player.rb
class Player < Participant
end

app/models/ranking.rb
class Ranking < ActiveRecord::Base
end

app/models/referee.rb
class Referee < Participant
	has_many :matches
end

app/models/season.rb
class Season < ActiveRecord::Base
end

app/models/show_team.rb
class ShowTeam < ActiveRecord::Base
end

app/models/team.rb
class Team < ActiveRecord::Base
  belongs_to :club
  belongs_to :referee
  has_many :matches

  has_many :participantTeams
  has_many :participants, :through => :participantTeams

  attr_accessible :name, :homeColor, :awayColor, :club_id

  def players 
  	self.participants.find(:all, :conditions => {:type => 'Player'})
  end

 def display_name
    "#{name} -  #{club.name}"
  end

  def coach
    self.participants.find_by_type("Coach")
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :nom
  has_many :microposts
end

app/models/win_lose.rb
class WinLose < ActiveRecord::Base
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Rails Bootstrap" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Rails Bootstrap" %>">
  <%= stylesheet_link_tag 	 "bootstrap", :media => 'all' %>
  <%= stylesheet_link_tag 	 "bootstrap-theme", :media => 'all' %>
  <%= javascript_include_tag "application" %>
  <%= javascript_include_tag "bootstrap" %>
  <%= csrf_meta_tags %>
  </head>
  <body>
  	    <div class="container">

      <!-- Static navbar -->
      <div class="navbar navbar-default" role="navigation">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#"><%= image_tag(image_path('logoWithoutText.png'),:width => "100px",:alt => "Logo") %></a>
        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "Clubs", controller: "clubs", action: "index" %></li>
            <li><%= link_to "Championnats", controller: "championships", action: "index" %></li>
            <li><%= link_to "Chronométreurs", controller: "timekeepers", action: "index" %></li>
            <li><%= link_to "Equipes", controller: "teams", action: "index" %></li>
            <li><%= link_to "Fédérations", controller: "federations", action: "index" %></li>
            <li><%= link_to "Salles", controller: "gyms", action: "index" %></li>
            <li><%= link_to "Matchs", controller: "matches", action: "index" %></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">Participants <b class="caret"></b></a>
              <ul class="dropdown-menu">	
              <li><%= link_to "Membres", controller: "members", action: "index" %></li>
        		  <li><%= link_to "Arbitres", referees_path %></li>
            	<li><%= link_to "Entraineurs", coaches_path %></li>
            	<li><%= link_to "Joueurs", players_path %></li>
              </ul>
             <li><%= link_to "Saisons", controller: "seasons", action: "index" %></li>
            </li>
             <% if signed_in? %>
                <li><%= link_to "Déco.", signout_path %></li>
              <% else %>
                <li><%= link_to "S'identifier", signin_path %></li>
              <% end %>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
      <% if flash[:error] -%>
        <p class='error'><%=h flash[:error] %></p>
      <% end -%>
      <% if flash[:notice] -%>
        <p class='error'><%=h flash[:error] %></p>
      <% end -%>


      <!-- Main component for a primary marketing message or call to action -->
      	<%= yield %>
        </p>


    </div> <!-- /container -->
    		

app/views/layouts/front_application.html.erb
<!DOCTYPE html>
<html lang="fr"> 
  <head>
      <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
      <meta name="description" content="Chron&Stats" />
      <title>Chron&Stats</title>
      <%= csrf_meta_tags %>
      <%= stylesheet_link_tag "style", :media => 'all' %>
      <%= javascript_include_tag "application" %>
  </head>
   <body>
    <!--start mainContainer-->
    <div id="mainContainer">
      <!--start header-->
      <div id="header">
        <div id="banner"><span>Chron&Stats</span> - Projet de groupe IL 2013</div>
      </div>
      <!--end header-->
      <!--start content-->
      <div id="outer">
        <!-- start menu -->
      <div id="menu">
        <ul class="menu-first-level">
          <li class="home-button">
            <%= 
            link_to root_path do
              image_tag "home.jpg", :alt => "Accueil"
            end
            %>
          </li>
          <% championships.each do |championship| %>
            <li>
              <a href="#" id="<%= championship.name.delete(" ") %>"><%= championship.name %></a>
            </li>
          <% end %>
        </ul>
        <% championships.each do |championship| %>
          <span class="info"><%= championship.name %></span>
          <ul class="menu-second-level" id="mnu_<%= championship.name.delete(" ") %>">
            <li>
              <%= link_to "Classement", controller: "stats", action: "show_ranking", championship_name: championship.name %>
            </li>
            <li>
              <%= link_to "Matchs joués", controller: "stats", action: "show_played_matches", championship_name: championship.name %>
            </li>
            <li>
              <%= link_to "Matchs à venir", controller: "stats", action: "show_future_matches", championship_name: championship.name %>
            </li>
            <li>
              <a href="#" id="link_equipes_<%= championship.name.delete(" ") %>">Equipes</a>
            </li>
          </ul>
          <ul class="menu-third-level" id="equipes_<%= championship.name.delete(" ") %>">
            <% chTeams.each do | team | 
              if team.championship_name == championship.name %>
                <li>
                  <%= 
                  link_to controller: "stats", action: "show_team", championship_name: championship.name, team_name: team.team_name  do
                    image_tag "#{team.team_name}.png", :alt => "Logo de l'équipe #{team.team_name}"
                  end
                  %>
                </li>
            <% end
            end %>
          </ul>
        <% end %>
      </div>
      <!-- end menu -->
      <div id="content">
        <%= yield %>
      </div>
      <!--end content-->

      <div id="footer">
        Copyright 2013 Chron&Stats | <%= link_to "Admin", controller: "clubs", action: "index" %>
      </div>  

    </div>
    <!--end mainContainer-->
  </body>
</html> 